name: Create Pull Request into gcp branch

on:
  push:
    branches:
      - k8s-tf
# jobs:
#   discover_repo:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check repository
#         run: echo "Repo is ${{ github.repository  }}"
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.repository}} == 'austinkaruru/k8s-the-hardway'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: actions/pull-request@v4
        with:
          title: 'Update gcp branch with changes from k8s-tf'
          body: 'This pull request updates the gcp branch with the latest changes from k8s-tf.'
