name: Create Pull Request into gcp branch

on:
  push:
    branches:
      - k8s-tf
permissions:
  contents: read
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.repository}} == 'austinkaruru/k8s-the-hardway'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base gcp \
            --head k8s-tf \
            --title "Update the gcp branch" \
            --body "This PR updates the gcp branch with the latest changes from the k8s-tf branch."





